---
title: 'Prepare FUMBBL roster data'
author: "Gertjan Verhoeven"
date: '2025-12-11'
params:
  group_name: "Third season"
  tournament_ruleset: "various"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# I. Loading package and data
## Load packages

```{r}
# Load packages
library(tidyverse)
```


## Read the data

We start with reading in the scraped FUMBBL roster data, this is generated by the `fumbbl_rosters` Jupyter Notebook.


```{r}
group_name <- params$group_name

df_rosters1 <- read.csv(file = "input/df_rosters_third_season_v3.csv")

df_rosters1$X <- NULL

df_rosters1$group_name <- group_name

# Cf. bb_tournament_settings.ods
tournament_ruleset <- params$tournament_ruleset

df_rosters1 <- df_rosters1 %>% filter(tournament_name != "Tellurian Christmas Brawl 2025")
```

```{r}
# bug fix
#df_rosters %>% filter(team_id == 161656)

```

# Use bbrosterplots function to add cost

```{r}
library(bbrosterplots)

#df_rosters <- df_rosters %>% select(-player_id) %>% ungroup() # PM BUGFIX
df_rosters1 <- df_rosters1 %>% rename(skill_name = skills)
df_rosters <- bbrosterplots::add_roster_metadata(df_rosters1, edition = "bb2025")

# check data
#write.csv(df_rosters, "df_rosters_3rded.csv")
```
```{r}
n_distinct(df_rosters$team_id)
```


# Use bbrosterplots to render plots and make pdf

```{r}
create_rosterplot(df_rosters, group_name = group_name, tournament_ruleset = tournament_ruleset)
```

```{r}
res <- df_rosters %>%
  group_by(coach_name, roster.name) %>%
  summarise(cnt = n()) %>%
  group_by(roster.name) %>%
  summarise(cnt = n()) %>%
  arrange(-cnt)

gp <- ggplot(res, aes(x = reorder(roster.name, cnt) ,y = cnt)) +
  geom_point() +
  expand_limits(y = 0) +
  coord_flip() +
  ylab("# rosters") +
  xlab("") +
  ggtitle("Third season Tournament roster popularity")

ggsave(gp, filename = "roster_pop_third_season.png")

gp
```

```{r}
res <- df_rosters %>%
  group_by(coach_name, tournament_name) %>%
  summarise(cnt = n()) %>%
  group_by(tournament_name) %>%
  summarise(cnt = n()) %>%
  arrange(-cnt)

gp <- ggplot(res, aes(x = reorder(tournament_name, cnt) ,y = cnt)) +
  geom_point() +
  expand_limits(y = 0) +
  coord_flip() +
  ylab("# rosters") +
  xlab("") +
  ggtitle("Third season Tournaments on Tourplay")

ggsave(gp, filename = "tournament_pop_third_season.png")
```

```{r}
#res <- file.copy(from = system.file("extdata", "EB25.jpg", package = "bbrosterplots"), to = ".")

races <- sort(unique(df_rosters$roster.name))

render_rosterbook(params = list(group_name = group_name, 
                                tournament_ruleset = tournament_ruleset, 
                                cover_image = "../blood-bowl-third-season-edition.jpeg",
                                scale_cover_perc = "50%",                                
                                races = races, 
                                perc = FALSE, 
                                team = FALSE), refresh_rmd = TRUE)
```
